### PR TITLE
docs: Add initial issue template and CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by henil**
Ideas of what more should be added are most welcomed :smile: 

The `CHANGELOG` part is for future use as we don't have proper releases at the moment.

### CODE REVIEW

**Comment by imsnif** [comment]
Hey @henil, this looks great!

A few comments:
1. I wouldn't add a section about the changelog before we have one. I feel it might be mostly confusing to people wanting to contribute.
2. I would very much like to encourage contributions from people new to open source and/or rust. What do you think about adding a section to CONTRIBUTING that would explain:
    * How to find something to work on (here we can point to our discord/matrix and say that if you are unsure what to do, we would be happy to help find something together and guide you through it)
    * How to contribute code (forking, pushing to your fork and opening a pull request - maybe here we can link to some external article?)

**Comment by henil** [comment]
> How to contribute code (forking, pushing to your fork and opening a pull request - maybe here we can link to some external article?)

@imsnif I think we can safely assume that the person looking at `CONTRIBUTING.md` would know about those things. I tried looking for an article that covers all these things but there are just too many ways (like Github Desktop or from Github UI or from the terminal) for a single article to cover it. And adding everything would add more noise to it than help. What do you think?

**Comment by imsnif** [comment]
> > How to contribute code (forking, pushing to your fork and opening a pull request - maybe here we can link to some external article?)
> 
> @imsnif I think we can safely assume that the person looking at `CONTRIBUTING.md` would know about those things. I tried looking for an article that covers all these things but there are just too many ways (like Github Desktop or from Github UI or from the terminal) for a single article to cover it. And adding everything would add more noise to it than help. What do you think?

I wouldn't assume a person looking through there knows these things, but I understand that providing all this information can be overwhelming. If there isn't a simple resource we can link to, maybe it wasn't such a good idea after all :)

**Comment by henil** [comment]
( I think this should be good for now. Later on, we can add PR templates )

**Pull request merged**
